[[headers]]
  for = "/*"
  [headers.values]
  Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/Media/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/Style/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/javaScript/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
